name: lightyear_chart_animation
description: "Lightyear chart animation"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  equatable: 2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
